USE contabeis;

SELECT REG_ANS AS Operadora, SUM(VL_SALDO_FINAL) - SUM(VL_SALDO_INICIAL) AS Despesas FROM contabeis_24_4
WHERE DESCRICAO = "EVENTOS/ SINISTROS CONHECIDOS OU AVISADOS  DE ASSISTÊNCIA A SAÚDE MEDICO HOSPITALAR "
GROUP BY REG_ANS
ORDER BY SUM(VL_SALDO_FINAL) - SUM(VL_SALDO_INICIAL)
LIMIT 10;

SELECT REG_ANS AS Operadora, SUM(VL_SALDO_FINAL) - SUM(VL_SALDO_INICIAL) AS Despesas 
FROM (
	SELECT REG_ANS, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL FROM contabeis_24_1
    UNION ALL
    SELECT REG_ANS, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL FROM contabeis_24_2
    UNION ALL
    SELECT REG_ANS, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL FROM contabeis_24_3
    UNION ALL
    SELECT REG_ANS, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL FROM contabeis_24_4
) as Total_2024
WHERE DESCRICAO = "EVENTOS/ SINISTROS CONHECIDOS OU AVISADOS  DE ASSISTÊNCIA A SAÚDE MEDICO HOSPITALAR "
GROUP BY REG_ANS
ORDER BY SUM(VL_SALDO_FINAL) - SUM(VL_SALDO_INICIAL)
LIMIT 10;