CREATE DATABASE IF NOT EXISTS contabeis;

USE contabeis;

CREATE TABLE contabeis_23_1 (
	id INT AUTO_INCREMENT PRIMARY KEY,
    DATA DATE,
	REG_ANS INT,
	CD_CONTA_CONTABIL INT,
	DESCRICAO TEXT(255),
	VL_SALDO_INICIAL NUMERIC(18,2),
	VL_SALDO_FINAL NUMERIC(18,2)
);

CREATE TABLE contabeis_23_2 (
	id INT AUTO_INCREMENT PRIMARY KEY,
    DATA DATE,
	REG_ANS INT,
	CD_CONTA_CONTABIL INT,
	DESCRICAO TEXT(255),
	VL_SALDO_INICIAL NUMERIC(18,2),
	VL_SALDO_FINAL NUMERIC(18,2)
);

CREATE TABLE contabeis_23_3 (
	id INT AUTO_INCREMENT PRIMARY KEY,
    DATA DATE,
	REG_ANS INT,
	CD_CONTA_CONTABIL INT,
	DESCRICAO TEXT(255),
	VL_SALDO_INICIAL NUMERIC(18,2),
	VL_SALDO_FINAL NUMERIC(18,2)
);

CREATE TABLE contabeis_23_4 (
	id INT AUTO_INCREMENT PRIMARY KEY,
    DATA DATE,
	REG_ANS INT,
	CD_CONTA_CONTABIL INT,
	DESCRICAO TEXT(255),
	VL_SALDO_INICIAL NUMERIC(18,2),
	VL_SALDO_FINAL NUMERIC(18,2)
);

CREATE TABLE contabeis_24_1 (
	id INT AUTO_INCREMENT PRIMARY KEY,
    DATA DATE,
	REG_ANS INT,
	CD_CONTA_CONTABIL INT,
	DESCRICAO TEXT(255),
	VL_SALDO_INICIAL NUMERIC(18,2),
	VL_SALDO_FINAL NUMERIC(18,2)
);

CREATE TABLE contabeis_24_2 (
	id INT AUTO_INCREMENT PRIMARY KEY,
    DATA DATE,
	REG_ANS INT,
	CD_CONTA_CONTABIL INT,
	DESCRICAO TEXT(255),
	VL_SALDO_INICIAL NUMERIC(18,2),
	VL_SALDO_FINAL NUMERIC(18,2)
);

CREATE TABLE contabeis_24_3 (
	id INT AUTO_INCREMENT PRIMARY KEY,
    DATA DATE,
	REG_ANS INT,
	CD_CONTA_CONTABIL INT,
	DESCRICAO TEXT(255),
	VL_SALDO_INICIAL NUMERIC(18,2),
	VL_SALDO_FINAL NUMERIC(18,2)
);

CREATE TABLE contabeis_24_4 (
	id INT AUTO_INCREMENT PRIMARY KEY,
    DATA DATE,
	REG_ANS INT,
	CD_CONTA_CONTABIL INT,
	DESCRICAO TEXT(255),
	VL_SALDO_INICIAL NUMERIC(18,2),
	VL_SALDO_FINAL NUMERIC(18,2)
);



